//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int idPartner { get; set; }
        public int TypePartner { get; set; }
        public string NamePartner { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
        public string Logo { get; set; }

        public string CorrectLogo
        {
            get
            {
                if (Logo != null)
                {
                    return $"/Images/{Logo}";
                }
                else
                {
                    return $"/Images/picture.png";
                }
            }
        }

        public string PercentSales
        {
            get
            {
                var product = PartnerProducts.FirstOrDefault();
                return product != null ? product.PercentSales : "0%";
            }
        }

        public string DisplayName
        {
            get
            {
                return $"{TypePartners?.NameType ?? "N/A"} | {NamePartner}";
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual TypePartners TypePartners { get; set; }
    }
}
