//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PartnerProducts
    {
        public int idPartnerProducts { get; set; }
        public string Production { get; set; }
        public int idPartner { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DataSales { get; set; }
    
        public virtual Partners Partners { get; set; }

        public string PercentSales
        {
            get
            {
                int totalQuantity = Partners?.PartnerProducts.Sum(p => p.Quantity) ?? 0;

                if (totalQuantity <= 10000)
                {
                    return "0%";
                }
                else if (totalQuantity <= 50000)
                {
                    return "5%";
                }
                else if (totalQuantity <= 300000)
                {
                    return "10%";
                }
                else
                {
                    return "15%";
                }
            }
        }
    }
}
